
declare -A RETRIEVE_TABLES=(
    ["001-Plans"]='id,value,queues,"createdAt",users,"updatedAt",name,connections'
    ["002-Companies"]='schedules,"dueDate",name,"updatedAt","createdAt",status,"planId",phone,recurrence,id,email'
    ["003-Users"]='"companyId",super,"passwordHash",email,"tokenVersion",profile,name,"createdAt",id,"updatedAt",online'
    ["004-Whatsapps"]='"greetingMessage",qrcode,plugged,token,retries,id,session,"updatedAt","ratingMessage","farewellMessage",provider,"companyId","isDefault",status,name,"complationMessage","createdAt","outOfHoursMessage",battery'
    ["005-Queues"]='color,schedules,name,"companyId","updatedAt","greetingMessage","createdAt",id,"outOfHoursMessage"'
    ["006-QueueOptions"]='title,"updatedAt","createdAt","queueId",message,"parentId",id,option'
    ["007-UserQueues"]='"queueId","updatedAt","userId","createdAt"'
    ["008-WhatsappQueues"]='"updatedAt","whatsappId","createdAt","queueId"'
    ["009-Contacts"]='email,"createdAt",id,"profilePicUrl","updatedAt",name,"isGroup","companyId",number'
    ["010-ContactCustomFields"]='id,"createdAt","contactId",name,value,"updatedAt"'
    ["011-Tickets"]='"companyId","isGroup","updatedAt","contactId",status,id,"unreadMessages","queueId","userId",uuid,"createdAt","queueOptionId","whatsappId","lastMessage",chatbot'
    ["012-Messages"]='"contactId",id,read,"companyId","createdAt",ack,"ticketId","mediaUrl","mediaType","quotedMsgId",participant,"queueId",body,"dataJson","updatedAt","isDeleted","remoteJid","fromMe"'
    ["013-Tags"]='"companyId","updatedAt",name,color,"createdAt",id'
    ["014-TicketTags"]='"tagId","createdAt","ticketId","updatedAt"'
    ["015-Chats"]='uuid,"createdAt","updatedAt","companyId",title,id,"ownerId","lastMessage"'
    ["016-ChatUsers"]='unreads,id,"updatedAt","createdAt","userId","chatId"'
    ["017-ChatMessages"]='"mediaName","createdAt","chatId","senderId","mediaPath",id,message,"updatedAt"'
    ["018-Settings"]='key,"companyId","updatedAt","createdAt",value,id'
)



#RETRIEVE_TABLES["Announcements"]='id,"mediaName","mediaPath","createdAt","updatedAt",status,text,title,priority,"companyId"'
#RETRIEVE_TABLES["Baileys"]='chats,"updatedAt","whatsappId","createdAt",contacts,id'
#RETRIEVE_TABLES["CampaignSettings"]='"createdAt",id,value,key,"companyId","updatedAt"'
#RETRIEVE_TABLES["CampaignShipping"]='"deliveredAt","contactId","campaignId","confirmationRequestedAt",number,"confirmedAt","createdAt","confirmationMessage","updatedAt","jobId",id,confirmation,message'
#RETRIEVE_TABLES["Campaigns"]='"createdAt","completedAt","scheduledAt",message1,"mediaPath","updatedAt","companyId",message4,name,"confirmationMessage2",confirmation,message3,"whatsappId","confirmationMessage1",message5,"confirmationMessage4",status,"confirmationMessage5","confirmationMessage3","contactListId","mediaName",id,message2'
#RETRIEVE_TABLES["ContactListItems"]='email,"contactListId","isWhatsappValid","companyId",name,"createdAt","updatedAt",id,number'
#RETRIEVE_TABLES["ContactLists"]='name,id,"updatedAt","createdAt","companyId"'
#RETRIEVE_TABLES["Helps"]='"updatedAt",description,link,"createdAt",title,id,video'
#RETRIEVE_TABLES["Invoices"]='status,id,detail,value,"companyId","createdAt","dueDate","updatedAt"'
#RETRIEVE_TABLES["QuickMessages"]='"companyId","createdAt","userId",id,"updatedAt",message,shortcode'
#RETRIEVE_TABLES["Schedules"]='id,"ticketId","contactId",status,"createdAt","updatedAt","sentAt",body,"companyId","userId","sendAt"'
#RETRIEVE_TABLES["SequelizeMeta"]='name'
#RETRIEVE_TABLES["Subscriptions"]='"whatsPriceCents","lastInvoiceUrl",id,"userPriceCents","createdAt","expiresAt","providerSubscriptionId","isActive","lastPlanChange","companyId","updatedAt"'
#RETRIEVE_TABLES["TicketNotes"]='"createdAt",id,"ticketId","updatedAt",note,"contactId","userId"'
#RETRIEVE_TABLES["TicketTraking"]='"updatedAt","finishedAt","startedAt","whatsappId","ticketId","companyId","ratingAt",rated,"queuedAt",id,"createdAt","userId"'
#RETRIEVE_TABLES["UserRatings"]='"userId","ticketId",rate,"companyId","createdAt",id,"updatedAt"'
